### ISSUE TITLE
Can react-flexmonster works with React v17.0.1?

### ISSUE THREAD

**Issue by normanwss** [flexmonster/pivot-react#14]
Well My project is using react v17.0.1,when I try to enable flexmonster into my project,it will prompt invalid hook call error.

Was it caused by react version?'casue flexmonster using react 16.13.1 while my project is 17.0.1

**Comment by VeraDidenko** [comment]
Hello, @normanwss,

Thank you for reaching out to us. 


Indeed, the `react-flexmonster` npm module needs to be updated to work with React 17.

Our team is currently looking into this case, and we will share the results with the ETA 26th of January.
Please feel free to reach out if any questions arise in the meantime.


Could you please let us know if you are [importing Flexmonster as a React Class Component](https://github.com/flexmonster/pivot-react/blob/master/ES6/src/components/ReactFlexmonsterExamples/UsingAPICalls.js#L3) in your project?
For example: `import * as FlexmonsterReact from 'react-flexmonster';`


Thank you, and looking forward to your response.

Kind regards, 
Vera

**Comment by normanwss** [comment]
@VeraDidenko hello,

Thanks for your response,here share my demo with react 17.0.1:

1.What it went wrong:
![image](https://user-images.githubusercontent.com/3325876/104691547-6b52a080-5741-11eb-9777-575ce362c2a4.png)

2.package.json:
![image](https://user-images.githubusercontent.com/3325876/104691598-7efe0700-5741-11eb-9d35-edd3049a4277.png)

3.How do I use Flexmonster in react-js(with hooks) file:
![image](https://user-images.githubusercontent.com/3325876/104691787-d9976300-5741-11eb-9079-221f69909018.png)


Yes I want to use Flexmonster with react hooks,you may want to know that it worked well if use react 16.13.0,but not in 17.0.1(prompted invalid hook calls)

If this is can be fixed,my boss is welcome to continue use Flexmonster,as it's really a good tool!

Thank you and looking your response too.

**Comment by VeraDidenko** [comment]
Hello, @normanwss,

 

Thank you for your response and for providing further details. 

 

Our team is currently working on the fix. We will share the results with the ETA 26th of January.

 

Also, could you please let us know your company name and if you are our client (this can be shared via email)? We need this information for our records. 

 

Thank you, and looking forward to your reply.

 

Kind regards,
Vera

**Comment by normanwss** [comment]
@VeraDidenko hi,

We haven't yet adopted Flexmonster officially(or say in our production),currently is for testing purose for new project,if it works well,I believe will use it finally.FYI,I have downgrade react to 16.13.0 to make it work well,and will change back to 17.0.1 after ETA 26th of Jan.

**Comment by VeraDidenko** [comment]
Hello, @normanwss,

 

Thank you for your reply. 

 

Our team is happy to hear that Flexmonster fits your needs.
We will notify you as soon as the fix is released on the 26th of January.

 

Kind regards,
Vera

**Comment by VeraDidenko** [comment]
Hello, @normanwss,

 

We are happy to inform you that our team has updated `react-flexmonster` to be compatible with React 17.0.1.

This is available in the latest version of Flexmonster: https://www.flexmonster.com/release-notes/.
You are welcome to update the component. Here is our updating to the latest version guide for assistance: https://www.flexmonster.com/doc/updating-to-the-latest-version/.

 

Also, our team would like to mention that the recommended approach is to import Flexmonster as a class component (even when using React Hooks): `import * as FlexmonsterReact from 'react-flexmonster';`

Using the `react-flexmonster` build instead of `react-flexmonster/hooks` is more reliable. 
When React rebuilds the DOM it will clear `react-flexmonster/hooks` state and `flexmonster()` function will return undefined.
For this reason, please consider using the `react-flexmonster` build instead of `react-flexmonster/hooks`, especially if [Flexmonster API calls](https://www.flexmonster.com/api/) need to be used.

 

Please let us know if the update works fine for you.
Looking forward to your response.

 
Kind regards, 
Vera

**Comment by normanwss** [comment]
@VeraDidenko hello,

Very appriciate for what you guys doing,thanks.
We will adopt Flexmonster officially after the evaluation(not a long time,may be in the incoming weeks).
Also will reply what happens after testing the newest version of Flexmonister,thanks again!

**Comment by VeraDidenko** [comment]
Hello, @normanwss,

 

Our team is wondering if you've found the latest update helpful.
Does Flexmonster work fine in React 17.0.1 on your end?

 

Please let us know if the fix works fine for you.
Looking forward to your feedback.

 

Kind regards, 
Vera

**Comment by normanwss** [comment]
@VeraDidenko hello

It's helpful after upgrade to latest version.Now still under eveluation,our team have listed a few technical qeustions,may I have your email address so that we can communicate via email message?Thanks.

**Comment by VeraDidenko** [comment]
Hello, @normanwss,

 

Thank you for your feedback.
Our team is happy to hear that the update works fine for you.

 

Regarding technical questions, we have a special communication channel via our support forum: [https://www.flexmonster.com/forum/](https://www.flexmonster.com/forum/).

Also, it is possible to communicate via email. In such a case, could you please provide your email address so that our team could contact you?

 

We are looking forward to hearing from you.

 

Kind regards, 
Vera
